CREATE DATABASE QuanLyRauSach
go

USE QuanLyRauSach
GO

CREATE TABLE PhanQuyen (
    MaPhanQuyen INTEGER IDENTITY NOT NULL,
    TenPhanQuyen NVARCHAR(50) NOT NULL,
    PRIMARY KEY (MaPhanQuyen)
);

CREATE TABLE TaiKhoan (
    MaTK INTEGER IDENTITY NOT NULL,
    TenDangNhap VARCHAR(50) NOT NULL,
    Matkhau VARCHAR(50) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    SDT VARCHAR(10) NOT NULL,
    AnhDaiDien VARCHAR(max),
    IsActive INTEGER NOT NULL,
    MaPhanQuyen INTEGER NOT NULL,
    PRIMARY KEY (MaTK),
    FOREIGN KEY (MaPhanQuyen) REFERENCES PhanQuyen(MaPhanQuyen)
);

CREATE TABLE TKNganHang (
    MaSoThe VARCHAR(50) NOT NULL,
    MaNH VARCHAR(10) NOT NULL,
    TenNH NVARCHAR(50) NOT NULL,
    TenChuThe NVARCHAR(50) NOT NULL,
    NgayCap DATE NOT NULL,
    NgayHetHan DATE NOT NULL,
    MaTK INTEGER NOT NULL,
    PRIMARY KEY (MaSoThe),
    FOREIGN KEY (MaTK) REFERENCES TaiKhoan(MaTK)
);

CREATE TABLE SieuThi (
    MaST VARCHAR(10) NOT NULL,
    TenST NVARCHAR(50) NOT NULL,
    PRIMARY KEY (MaST)
);

CREATE TABLE NhaCungCap (
    MaNCC VARCHAR(10) NOT NULL,
    TenNCC NVARCHAR(50) NOT NULL,
    MoTa TEXT NOT NULL,
    MaSoThue VARCHAR(50) NOT NULL,
    MaGPKD VARCHAR(50) NOT NULL,
    AnhGPKD VARCHAR(max),
    NgayDangKy DATE NOT NULL,
    PRIMARY KEY (MaNCC)
);

CREATE TABLE NhanVienNCC (
    MaNV VARCHAR(10) NOT NULL,
    TenNV NVARCHAR(50) NOT NULL,
    ChucVu NVARCHAR(50) NOT NULL,
    MaNCC VARCHAR(10) NOT NULL,
    MaTK INTEGER UNIQUE NOT NULL,
    PRIMARY KEY (MaNV),
    FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC),
    FOREIGN KEY (MaTK) REFERENCES TaiKhoan(MaTK)
);

CREATE TABLE NhanVienST (
    MaNV VARCHAR(10) NOT NULL,
    TenNV NVARCHAR(50) NOT NULL,
    ChucVu NVARCHAR(50) NOT NULL,
    MaST VARCHAR(10) NOT NULL,
    MaTK INTEGER NOT NULL,
    PRIMARY KEY (MaNV),
    FOREIGN KEY (MaST) REFERENCES SieuThi(MaST),
    FOREIGN KEY (MaTK) REFERENCES TaiKhoan(MaTK)
);

CREATE TABLE DiaCHiST (
    MaDC INTEGER IDENTITY NOT NULL,
    TenDuong TEXT NOT NULL,
    PhuongXa TEXT NOT NULL,
    QuanHuyen TEXT NOT NULL,
    ThanhPho TEXT NOT NULL,
    MaST VARCHAR(10) NOT NULL,
    PRIMARY KEY (MaDC),
    FOREIGN KEY (MaST) REFERENCES SieuThi(MaST)
);

CREATE TABLE DiaChiNCC (
    MaDC INTEGER IDENTITY NOT NULL,
    TenDuong TEXT NOT NULL,
    PhuongXa TEXT NOT NULL,
    QuanHuyen TEXT NOT NULL,
    ThanhPho TEXT NOT NULL,
    MaNCC VARCHAR(10) NOT NULL,
    PRIMARY KEY (MaDC),
    FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC)
);

CREATE TABLE DanhMuc (
    MaDanhMuc INTEGER IDENTITY NOT NULL,
    TenDanhMuc NVARCHAR(50) NOT NULL,
    MoTa TEXT NOT NULL,
    PRIMARY KEY (MaDanhMuc)
);

CREATE TABLE MatHang (
    MaMH VARCHAR(10) NOT NULL,
    MaDM INTEGER NOT NULL,
    TenMH NVARCHAR(50) NOT NULL,
    MoTa TEXT,
    DonViTinh NVARCHAR(50) NOT NULL,
    Dongia DECIMAL(18, 0) NOT NULL,
    SoLuong INTEGER NOT NULL,
    TGBaoQuan NVARCHAR(50) NOT NULL,
    TinhTrang INTEGER NOT NULL,
    PRIMARY KEY (MaMH),
    FOREIGN KEY (MaDM) REFERENCES DanhMuc(MaDanhMuc)
);

CREATE TABLE HinhAnhMatHang (
    MaHAMH INTEGER IDENTITY NOT NULL,
    DuongDanHinhAnh TEXT NOT NULL,
    MaMH VARCHAR(10) NOT NULL,
    PRIMARY KEY (MaHAMH),
    FOREIGN KEY (MaMH) REFERENCES MatHang(MaMH)
);

CREATE TABLE ChiTietCungUng (
    MaNVNCC VARCHAR(10) NOT NULL,
    MaMH VARCHAR(10) NOT NULL,
    SoLuongCungUng INTEGER NOT NULL,
    PRIMARY KEY (MaNVNCC, MaMH),
    FOREIGN KEY (MaNVNCC) REFERENCES NhanVienNCC(MaNV),
    FOREIGN KEY (MaMH) REFERENCES MatHang(MaMH)
);

CREATE TABLE DonHang (
    MaDH INTEGER IDENTITY NOT NULL,
    MaNVST VARCHAR(10) NOT NULL,
    MaNVNCC VARCHAR(10) NOT NULL,
    NgayDat DATE NOT NULL,
    NgayGiaoHang DATE,
    TGTaoDon DATETIME NOT NULL,
    TGThanhToan DATETIME,
    DiaChiNhan TEXT NOT NULL,
    GhiChu TEXT,
    HinhThucThanhToan NVARCHAR(50) NOT NULL,
    TrangThaiDH NVARCHAR(50) NOT NULL,
    TTDoiTra INTEGER NOT NULL,
    PRIMARY KEY (MaDH),
    FOREIGN KEY (MaNVST) REFERENCES NhanVienST(MaNV),
    FOREIGN KEY (MaNVNCC) REFERENCES NhanVienNCC(MaNV)
);

CREATE TABLE ChiTietDonHang (
    MaDH INTEGER NOT NULL,
    MaMH VARCHAR(10) NOT NULL,
    SoLuongDat INTEGER NOT NULL,
    DonGia DECIMAL(18,0) NOT NULL,
    PRIMARY KEY (MaDH, MaMH),
    FOREIGN KEY (MaDH) REFERENCES DonHang(MaDH),
    FOREIGN KEY (MaMH) REFERENCES MatHang(MaMH)
);

CREATE TABLE HoaDon (
    MaHD INTEGER IDENTITY NOT NULL,
    MaDH INTEGER NOT NULL,
    MaNVGH VARCHAR(10) NOT NULL,
    NgayTaoHD DATE NOT NULL,
    TongTien DECIMAL(18,0) NOT NULL,
    PhuongThucThanhToan NVARCHAR(50) NOT NULL,
    GhiChu TEXT,
    PRIMARY KEY (MaHD),
    FOREIGN KEY (MaDH) REFERENCES DonHang(MaDH),
	FOREIGN KEY (MaNVGH) REFERENCES NhanVienNCC(MaNV)
);